<div class="login-box-body">
    <p class="login-box-msg">Esqueceu sua senha? Crie uma nova.</p>
    <?php
    echo $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible']);
    echo $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible']);
    ?>

    <?= $this->form()->openTag($this->form); ?>
    <div class="form-group <?= $this->formElementErrors($this->form->get('password')) ? 'has-error' : ''; ?> has-feedback">
        <?= $this->formPassword($this->form->get('password')); ?>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        <?= $this->formElementErrors($this->form->get('password')); ?>
    </div>
    <div class="form-group <?= $this->formElementErrors($this->form->get('verifyPassword')) ? 'has-error' : ''; ?> has-feedback">
        <?= $this->formPassword($this->form->get('verifyPassword')); ?>
        <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
        <?= $this->formElementErrors($this->form->get('verifyPassword')); ?>
    </div>
    <?= $this->formHidden($this->form->get('csrf')); ?>
    <div class="row">
        <div class="pull-right col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Nova senha</button>
        </div>
    </div>
    <?= $this->form()->closeTag(); ?>

    <a href="login.html">Voltar para login</a><br>

</div>