<div class="login-box-body">
    <p class="login-box-msg">Esqueceu sua senha? Crie uma nova.</p>

    <?php
    echo $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible']);
    echo $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible']);
    ?>

    <?= $this->form()->openTag($this->form); ?>
    <div class="form-group <?= $this->formElementErrors($this->form->get('email')) ? 'has-error' : ''; ?> has-feedback">
        <?= $this->formEmail($this->form->get('email')); ?>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        <?= $this->formElementErrors($this->form->get('email')); ?>
    </div>
    <?= $this->formHidden($this->form->get('csrf')); ?>
    <div class="row">
        <div class="pull-right col-xs-5">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Nova senha</button>
        </div>
    </div>
    <?= $this->form()->closeTag(); ?>

    <a href="#">Voltar para login</a><br>

</div>